version: "3.9"
services: 
  mysql-db:
    image: mysql
    container_name: booking-app-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: booking_app_db

  api:
    build: ./api
    container_name: booking-app-api-container
    restart: always
    environment:
      - DATABASE_HOST=booking-app-db-container
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=booking_app_db
      - DATABASE_PORT=3306
      - MAIL_USERNAME=santiagodorado@unicauca.edu.co
      - MAIL_PASSWORD=vqolkxtldgogklfc
    ports:
     - "8080:8080"
    depends_on:
      - mysql-db
  consumer:
    build: ./consumer
    container_name: booking-app-consumer-container
    restart: always
    environment:
      - BOOKING_API_URL=http://booking-app-api-container:8080
      - RABBITMQ_HOST=booking-app-rabbitmq-container
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
      - producer
      - api 
  producer:
    build: ./producer
    container_name: booking-app-producer-container
    restart: always
    environment:
      - BOOKING_API_URL=http://booking-app-api-container:8080
      - RABBITMQ_HOST=booking-app-rabbitmq-container
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
      - api
    ports:
      - "8081:8081"

  rabbitmq:
    container_name: booking-app-rabbitmq-container
    restart: always
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"