version: "3.9"
services: 
  mysql-db:
    image: mysql
    container_name: booking-app-db-container
    restart: always
    env_file:
      - ./env/database.env
    volumes:
      - data-volume:/var/lib/mysql
  api:
    build: ./api
    container_name: booking-app-api-container
    restart: always
    env_file:
      - ./env/api.env
    depends_on:
      - mysql-db
  consumer:
    build: ./consumer
    container_name: booking-app-consumer-container
    restart: always
    env_file:
      - ./env/consumer.env
    depends_on:
      - rabbitmq
      - producer
      - api 
  producer:
    build: ./producer
    container_name: booking-app-producer-container
    restart: always
    env_file:
      - ./env/producer.env
    depends_on:
      - rabbitmq
      - api
    ports:
      - "8081:8081"

  rabbitmq:
    container_name: booking-app-rabbitmq-container
    restart: always
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queue-volume:/var/lib/rabbitmq
volumes:
  data-volume:
  queue-volume: